services:
  db:
    image: postgres:16
    container_name: medvault-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medvault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: medvault-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/medvault
      JWT_SECRET_KEY: SuperSecret
      JWT_ALGORITHM: HS256
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build: ./medvault-frontend
    container_name: medvault-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./medvault-frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1

volumes:
  pgdata: