"""add_metric_cache_fks_and_fix_user_boolean

Revision ID: 07892be40df6
Revises: 001
Create Date: 2026-02-26 19:49:10.964902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07892be40df6'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_hospital_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_flow_events_department_timestamp', 'flow_events', ['department_id', 'timestamp'], unique=False)
    op.create_index('ix_flow_events_hospital_timestamp', 'flow_events', ['hospital_id', 'timestamp'], unique=False)
    op.create_index('ix_flow_events_patient_timestamp', 'flow_events', ['patient_id', 'timestamp'], unique=False)
    op.create_index('ix_flow_events_resource_timestamp', 'flow_events', ['resource_id', 'timestamp'], unique=False)
    op.drop_constraint(op.f('flow_events_resource_id_fkey'), 'flow_events', type_='foreignkey')
    op.drop_constraint(op.f('flow_events_department_id_fkey'), 'flow_events', type_='foreignkey')
    op.drop_constraint(op.f('flow_events_hospital_id_fkey'), 'flow_events', type_='foreignkey')
    op.create_foreign_key(None, 'flow_events', 'resources', ['resource_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'flow_events', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flow_events', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('metrics_cache_resource_id_fkey'), 'metrics_cache', type_='foreignkey')
    op.drop_constraint(op.f('metrics_cache_department_id_fkey'), 'metrics_cache', type_='foreignkey')
    op.drop_constraint(op.f('metrics_cache_hospital_id_fkey'), 'metrics_cache', type_='foreignkey')
    op.create_foreign_key(None, 'metrics_cache', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'metrics_cache', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'metrics_cache', 'resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'metrics_cache',
        existing_comment='Cached metric values for performance',
        schema=None
    )
    op.drop_constraint(op.f('resources_department_id_fkey'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using='is_active::boolean',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('resources_department_id_fkey'), 'resources', 'departments', ['department_id'], ['id'])
    op.create_table_comment(
        'metrics_cache',
        'Cached metric values for performance',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'metrics_cache', type_='foreignkey')
    op.drop_constraint(None, 'metrics_cache', type_='foreignkey')
    op.drop_constraint(None, 'metrics_cache', type_='foreignkey')
    op.create_foreign_key(op.f('metrics_cache_hospital_id_fkey'), 'metrics_cache', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(op.f('metrics_cache_department_id_fkey'), 'metrics_cache', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('metrics_cache_resource_id_fkey'), 'metrics_cache', 'resources', ['resource_id'], ['id'])
    op.drop_constraint(None, 'flow_events', type_='foreignkey')
    op.drop_constraint(None, 'flow_events', type_='foreignkey')
    op.drop_constraint(None, 'flow_events', type_='foreignkey')
    op.create_foreign_key(op.f('flow_events_hospital_id_fkey'), 'flow_events', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(op.f('flow_events_department_id_fkey'), 'flow_events', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('flow_events_resource_id_fkey'), 'flow_events', 'resources', ['resource_id'], ['id'])
    op.drop_index('ix_flow_events_resource_timestamp', table_name='flow_events')
    op.drop_index('ix_flow_events_patient_timestamp', table_name='flow_events')
    op.drop_index('ix_flow_events_hospital_timestamp', table_name='flow_events')
    op.drop_index('ix_flow_events_department_timestamp', table_name='flow_events')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_hospital_id_fkey'), 'departments', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###
