"""add_metric_cache_fks_and_fix_user_boolean

Revision ID: c5fa88cff966
Revises: 07892be40df6
Create Date: 2026-02-26 19:57:45.291504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fa88cff966'
down_revision = '07892be40df6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
